### ISSUE TITLE
[PENDING] Update screenshot

### ISSUE THREAD

**Issue by sergeevabc** [mrchimp/mdr#11]
Dear Jake,
Screenshot listed in [README.md][1] is missing.

[1]: https://github.com/mrchimp/mdr/blob/master/README.md

**Comment by mrchimp** [comment]
Thanks for the heads up. My site is down at the moment.

On 18 Dec 2016 4:00 a.m., "Aleksandr" <notifications@github.com> wrote:

Dear Jake,
It seems the screenshot listed in README.md
<https://github.com/mrchimp/mdr/blob/master/README.md> is missing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrchimp/mdr/issues/11>, or mute the thread

**Comment by sergeevabc** [comment]
Is there anything a mere user like me could do to expedite a resolution of this issue?

**Comment by mrchimp** [comment]
Sure, open test.md in mdr, take a screenshot, post it to imgur (or
somewhere like that) and send a pull request with an updated readme.md.

That said, I've finished work for the year now so I'll have time to sort
out my site.

**Comment by mrchimp** [comment]
Fixed!

**Comment by sergeevabc** [comment]
Is it correct there is no way to compile **mdr** as standalone ```.exe``` for Windows?

**Comment by mrchimp** [comment]
You could probably do it with EncloseJS or something but it's not something I've tried.

**Comment by sergeevabc** [comment]
It’s sad. Windows CLI definitely lacks a good MD viewer.
Current workaround is ```pandoc text.md > "%temp%\markdown.html" && links "%temp%\markdown.html" ```

**Comment by mrchimp** [comment]
Does `npm install -g mdr` not work on windows?

**Comment by sergeevabc** [comment]
Perhaps. Thing is I’m looking for standalone executables to be portable, i.e. to run from USB stick.

**Comment by sergeevabc** [comment]
Still no way to get [b]mdr[/b] as standalone binary?

**Comment by mrchimp** [comment]
If someone can find a way to do it I'm happy to accept pull requests but it's not on my list I'm afraid.
